### PR TITLE
feat(electricity-map-data)

### PR DESCRIPTION
**Pull request by dvelasquez**
This PR drops the data from the [European Energy Grid](https://www.eea.europa.eu/data-and-maps/daviz/co2-emission-intensity-5#tab-chart_2) since it has not been updated since 2016.

I'm adding the data from [Electricity Map](https://www.electricitymap.org/) with permission of the authors.

I'm adding also the Credits section at the end, please let me know if is ok for you @tth4vb

### CODE REVIEW

**Comment by tth4vb** [comment]
@dvelasquez what values did you use here from electricityMap? Just want to make sure you've got the right numbers :)

**Comment by dvelasquez** [comment]
Yes, for now I just copied the data from the API response.

In the future would be ideal to download the json payload once a month.

**Comment by tth4vb** [comment]
Ok, the issue here is that you're getting a snapshot in time on an hourly basis, and depending on the region this could vary a lot hour by hour, so i'd suggest you use a 24-hour average or find a yearly source somewhere else like the IEA :)

**Comment by dvelasquez** [comment]
> Ok, the issue here is that you're getting a snapshot in time on an hourly basis, and depending on the region this could vary a lot hour by hour, so i'd suggest you use a 24-hour average or find a yearly source somewhere else like the IEA :)

I will gather hourly values for a couple of days (maybe a month) and then update the values of the library.

Thanks for your feedback!

**Comment by dvelasquez** [comment]
After some time I've gathered the data every hour for several days. Now I have a day, but once I have a month I will update the data with that.

Thanks very much for your help @tth4vb!

**Pull request merged**
